# Generated by Django 5.1.15 on 2026-05-29 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_officelocation_allowed_ips'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='work_days',
            field=models.CharField(default='1,2,3,4,5', help_text='Vergul bilan: 1=Du, 2=Se, 3=Ch, 4=Pa, 5=Ju, 6=Sha, 7=Ya. Masalan 5 kunlik: 1,2,3,4,5 | 6 kunlik: 1,2,3,4,5,6', max_length=20, verbose_name='Ish kunlari'),
        ),
    ]
