# Generated by Django 5.1.15 on 2026-05-29 08:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_work_days'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='department',
            options={'ordering': ['name'], 'verbose_name': "Bo'lim", 'verbose_name_plural': "Bo'limlar"},
        ),
        migrations.AlterModelOptions(
            name='officelocation',
            options={'ordering': ['name'], 'verbose_name': 'Ofis joyi', 'verbose_name_plural': 'Ofis joylari'},
        ),
        migrations.AlterModelOptions(
            name='shift',
            options={'ordering': ['name'], 'verbose_name': 'Smena', 'verbose_name_plural': 'Smenalar'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['first_name', 'last_name', 'id'], 'verbose_name': 'Foydalanuvchi', 'verbose_name_plural': 'Foydalanuvchilar'},
        ),
    ]
