# Generated by Django 5.1.15 on 2026-06-01 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_department_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='face_descriptor',
            field=models.TextField(blank=True, default='', help_text="face-api.js 128-dim deskriptor JSON formatda. Bo'sh bo'lsa yuz ro'yxatdan o'tmagan.", verbose_name='Yuz kodi (128-dim JSON)'),
        ),
        migrations.AddField(
            model_name='user',
            name='face_registered_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name="Yuz ro'yxatdan o'tgan vaqt"),
        ),
    ]
