# Generated by Django 5.1.15 on 2026-06-09 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_user_face_descriptor_user_face_registered_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='face_photo',
            field=models.ImageField(blank=True, null=True, upload_to='face_photos/', verbose_name='Yuz rasmi'),
        ),
        migrations.AlterField(
            model_name='user',
            name='face_descriptor',
            field=models.TextField(blank=True, default='', help_text='face-api.js 128-dim deskriptor JSON formatda.', verbose_name='Yuz kodi (128-dim JSON)'),
        ),
    ]
