# Generated by Django 5.1.15 on 2026-07-15 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_user_face_photo_alter_user_face_descriptor'),
    ]

    operations = [
        migrations.AddField(
            model_name='shift',
            name='break_end',
            field=models.TimeField(blank=True, null=True, verbose_name='Tanaffus tugashi'),
        ),
        migrations.AddField(
            model_name='shift',
            name='break_start',
            field=models.TimeField(blank=True, null=True, verbose_name='Tanaffus boshlanishi'),
        ),
    ]
