# Generated by Django 5.1.15 on 2026-05-29 08:31

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='monthlypayroll',
            name='absence_deduction',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12, verbose_name='Kelmagan kun ayirmasi'),
        ),
        migrations.AddField(
            model_name='monthlypayroll',
            name='per_day_rate',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12, verbose_name='Kunlik stavka'),
        ),
        migrations.AddField(
            model_name='monthlypayroll',
            name='work_days_total',
            field=models.PositiveIntegerField(default=0, verbose_name='Oydagi ish kunlari'),
        ),
        migrations.AlterField(
            model_name='monthlypayroll',
            name='absent_days',
            field=models.PositiveIntegerField(default=0, verbose_name='Kelmagan kunlar'),
        ),
        migrations.AlterField(
            model_name='monthlypayroll',
            name='base_salary',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12, verbose_name='Asosiy oylik'),
        ),
        migrations.AlterField(
            model_name='monthlypayroll',
            name='bonus_total',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12, verbose_name='Bonus'),
        ),
        migrations.AlterField(
            model_name='monthlypayroll',
            name='late_minutes',
            field=models.PositiveIntegerField(default=0, verbose_name='Kechikish (daq)'),
        ),
        migrations.AlterField(
            model_name='monthlypayroll',
            name='late_penalty_total',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12, verbose_name='Kechikish jarimasi'),
        ),
        migrations.AlterField(
            model_name='monthlypayroll',
            name='penalty_total',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12, verbose_name='Jarima'),
        ),
        migrations.AlterField(
            model_name='monthlypayroll',
            name='total',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12, verbose_name='Yakuniy summa'),
        ),
        migrations.AlterField(
            model_name='monthlypayroll',
            name='weekend_days',
            field=models.PositiveIntegerField(default=0, verbose_name='Dam olish ishlagan'),
        ),
        migrations.AlterField(
            model_name='monthlypayroll',
            name='weekend_extra',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12, verbose_name="Dam olish qo'shimchasi"),
        ),
        migrations.AlterField(
            model_name='monthlypayroll',
            name='worked_days',
            field=models.PositiveIntegerField(default=0, verbose_name='Ishlangan kunlar'),
        ),
    ]
